# Generated by Django 4.2.7 on 2025-04-10 19:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=32, populate_from='name', unique=True),
        ),
    ]
