# Generated by Django 4.2.7 on 2025-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='code',
            field=models.CharField(default='eb3', max_length=10, unique=True),
        ),
    ]
