# Generated by Django 4.2.7 on 2025-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='code',
            field=models.CharField(default='WDK', max_length=10, unique=True),
        ),
    ]
