# Generated by Django 4.2.7 on 2025-04-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coocing_time',
            new_name='coocking_time',
        ),
    ]
