# Generated by Django 4.2.7 on 2025-04-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0001_initial'),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientInRecipe',
        ),
    ]
