# Generated by Django 4.2.7 on 2025-04-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_coocing_time_recipe_coocking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coocking_time',
            new_name='cooking_time',
        ),
    ]
