# Generated by Django 4.2.7 on 2025-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='code',
            field=models.CharField(default='r3b', max_length=10, unique=True),
        ),
    ]
