# Generated by Django 4.2.7 on 2025-04-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_shortlink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='code',
            field=models.CharField(default='bYD', max_length=10, unique=True),
        ),
    ]
